apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway
      timeout: 60
      #jsonData:
      #  maxLines: 1000
      #  derivedFields:
      #  - datasourceUid: Tempo
      #    matcherRegex: "traceID=(\\w+)"
      #    name: TraceID
      #    # url will be interpreted as query for the datasource
      #    url: '$${__value.raw}'
      #    urlDisplayLabel: 'View trace'

