name: Package and Push Helm Chart

on:
  push:
    tags:
      - '*'
  #    - 'v*'
  #   branches:
  #   - "main"
  # workflow_dispatch:

jobs:
  helm-chart:
    runs-on: ubuntu-latest
    permissions:
      packages: write # push helm chart
      contents: write # create release

    steps:
    - uses: actions/checkout@v4
      name: Clonar o repo

    - name: Package
      run: |
        export PACKAGE_FILENAME=$(docker run --rm -v ${PWD}:/current_dir -w /current_dir --user $(id -u):$(id -g) alpine/helm package . | awk '{ print $NF }' | xargs basename)
        echo "PACKAGE_FILENAME=$PACKAGE_FILENAME" >> $GITHUB_ENV

    - name: Push
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
        helm push $PACKAGE_FILENAME oci://ghcr.io/${{ github.repository_owner }}
        # helm install YOUR_RELEASE_NAME oci://ghcr.io/${{ github.repository_owner }}/YOUR_CHART_NAME --version YOUR_VERSION

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          # Release Notes for ${{ github.ref_name }}

          This release corresponds to tag ${{ github.ref_name }}.
        draft: false
        prerelease: false
